# Generated by Django 6.0 on 2025-12-17 06:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0002_alter_todoitem_created_at_alter_todoitem_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('singer', models.CharField(max_length=255)),
                ('writer', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('released_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'music',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='TodoItem',
        ),
    ]
